# Generated by Django 6.0.8 on 2026-09-05 09:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={},
        ),
        migrations.RemoveField(
            model_name='habit',
            name='duration_sec',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='linked_habit',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='periodicity',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='habit',
            name='duration',
            field=models.PositiveSmallIntegerField(default=120, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)], verbose_name='Длительность (секунды)'),
        ),
        migrations.AddField(
            model_name='habit',
            name='frequency',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='Периодичность (дней)'),
        ),
        migrations.AddField(
            model_name='habit',
            name='related_habit',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_pleasant': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='Связанная привычка'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='is_pleasant',
            field=models.BooleanField(default=False, verbose_name='Приятная привычка'),
        ),
    ]
