# Generated by Django 6.0.8 on 2026-09-05 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habit_options_remove_habit_duration_sec_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='related_habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='Связанная привычка'),
        ),
    ]
