# Generated by Django 6.0.8 on 2026-09-21 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habit_related_habit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ['-id']},
        ),
    ]
